inferences:
  inf-20251028-060317:
    id: inf-20251028-060317
    created: '2025-10-28T06:03:17.556676Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: dog_0700.jpg
    output_path: predictions/inf-20251028-060317
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: failed
    stats: null
    error: No module named 'inference'
  inf-20251028-060507:
    id: inf-20251028-060507
    created: '2025-10-28T06:05:07.553121Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: dog_0700.jpg
    output_path: predictions/inf-20251028-060507
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: pending
    stats: null
  inf-20251028-060932:
    id: inf-20251028-060932
    created: '2025-10-28T06:09:32.019185Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: dog_0700.jpg
    output_path: predictions/inf-20251028-060932
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 0
      avg_inference_time_ms: 197.9
      classes_detected: []
  inf-20251029-005826:
    id: inf-20251029-005826
    created: '2025-10-29T00:58:26.437830Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: ./dog_0700.jpg
    output_path: predictions/inf-20251029-005826
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 0
      avg_inference_time_ms: 254.77
      classes_detected: []
  inf-20251029-005846:
    id: inf-20251029-005846
    created: '2025-10-29T00:58:46.725632Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: ./dog_0700.jpg
    output_path: predictions/inf-20251029-005846
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 0
      avg_inference_time_ms: 164.35
      classes_detected: []
  inf-20251029-012642:
    id: inf-20251029-012642
    created: '2025-10-29T01:26:42.626125Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: download.svg
    output_path: predictions/inf-20251029-012642
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: failed
    stats: null
    error: 'No images found in: download.svg'
  inf-20251029-012658:
    id: inf-20251029-012658
    created: '2025-10-29T01:26:58.193637Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: fruit_0000.jpg
    output_path: predictions/inf-20251029-012658
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: failed
    stats: null
    error: 'No images found in: fruit_0000.jpg'
  inf-20251029-013744:
    id: inf-20251029-013744
    created: '2025-10-29T01:37:44.881274Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_213744
    output_path: predictions/inf-20251029-013744
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: failed
    stats: null
    error: '[Errno 21] Is a directory: ''/Users/malikmacbook/Desktop/ModelCub/lmfao/data/uploads/predictions/20251028_213744'''
  inf-20251029-014121:
    id: inf-20251029-014121
    created: '2025-10-29T01:41:21.158158Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_214121/fruit_0002.jpg
    output_path: predictions/inf-20251029-014121
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 0
      avg_inference_time_ms: 237.3
      classes_detected: []
  inf-20251029-014913:
    id: inf-20251029-014913
    created: '2025-10-29T01:49:13.768152Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_214913/fruit_0000.jpg
    output_path: predictions/inf-20251029-014913
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 0
      avg_inference_time_ms: 217.36
      classes_detected: []
  inf-20251029-015035:
    id: inf-20251029-015035
    created: '2025-10-29T01:50:35.047699Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_215035/fruit_0008.jpg
    output_path: predictions/inf-20251029-015035
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: true
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 0
      avg_inference_time_ms: 252.94
      classes_detected: []
  inf-20251029-015052:
    id: inf-20251029-015052
    created: '2025-10-29T01:50:52.113528Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_215052/fruit_0012.jpg
    output_path: predictions/inf-20251029-015052
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: true
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 0
      avg_inference_time_ms: 156.79
      classes_detected: []
  inf-20251029-022351:
    id: inf-20251029-022351
    created: '2025-10-29T02:23:51.857885Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_222351/fruit_0002.jpg
    output_path: predictions/inf-20251029-022351
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 0
      avg_inference_time_ms: 260.94
      classes_detected: []
  inf-20251029-022409:
    id: inf-20251029-022409
    created: '2025-10-29T02:24:09.326481Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_222409/fruit_0013.jpg
    output_path: predictions/inf-20251029-022409
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 0
      avg_inference_time_ms: 155.57
      classes_detected: []
  inf-20251029-023056:
    id: inf-20251029-023056
    created: '2025-10-29T02:30:56.532294Z'
    model_source: lallalala
    model_path: models/lallalala/best.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_223056/fruit_0021.jpg
    output_path: predictions/inf-20251029-023056
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 0
      avg_inference_time_ms: 241.74
      classes_detected: []
  inf-20251029-031407:
    id: inf-20251029-031407
    created: '2025-10-29T03:14:07.134188Z'
    model_source: from-import
    model_path: models/from-import/model.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_231407/fruit_0159.jpg
    output_path: predictions/inf-20251029-031407
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: true
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 1
      avg_inference_time_ms: 290.38
      classes_detected:
      - person
  inf-20251029-031503:
    id: inf-20251029-031503
    created: '2025-10-29T03:15:03.078347Z'
    model_source: from-import
    model_path: models/from-import/model.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_231503/fruit_0003.jpg
    output_path: predictions/inf-20251029-031503
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: true
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 1
      avg_inference_time_ms: 166.19
      classes_detected:
      - orange
  inf-20251029-031517:
    id: inf-20251029-031517
    created: '2025-10-29T03:15:17.095469Z'
    model_source: from-import
    model_path: models/from-import/model.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_231517/fruit_0002.jpg
    output_path: predictions/inf-20251029-031517
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: true
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 0
      avg_inference_time_ms: 169.79
      classes_detected: []
  inf-20251029-032441:
    id: inf-20251029-032441
    created: '2025-10-29T03:24:41.499128Z'
    model_source: from-import
    model_path: models/from-import/model.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_232441/fruit_0000.jpg
    output_path: predictions/inf-20251029-032441
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 1
      avg_inference_time_ms: 221.5
      classes_detected:
      - cake
  inf-20251029-032513:
    id: inf-20251029-032513
    created: '2025-10-29T03:25:13.187489Z'
    model_source: from-import
    model_path: models/from-import/model.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_232513/fruit_0000.jpg
    output_path: predictions/inf-20251029-032513
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: true
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 1
      avg_inference_time_ms: 155.96
      classes_detected:
      - cake
  inf-20251029-033204:
    id: inf-20251029-033204
    created: '2025-10-29T03:32:04.341758Z'
    model_source: from-import
    model_path: models/from-import/model.pt
    input_type: image
    input_path: data/uploads/predictions/20251028_233204/fruit_0004.jpg
    output_path: predictions/inf-20251029-033204
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: true
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 1
      avg_inference_time_ms: 231.58
      classes_detected:
      - cake
  inf-20251029-040835:
    id: inf-20251029-040835
    created: '2025-10-29T04:08:35.166835Z'
    model_source: from-import
    model_path: models/from-import/model.pt
    input_type: image
    input_path: data/uploads/predictions/20251029_000835/polar_bear99.jpg
    output_path: predictions/inf-20251029-040835
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: true
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 0
      avg_inference_time_ms: 292.9
      classes_detected: []
  inf-20251029-040851:
    id: inf-20251029-040851
    created: '2025-10-29T04:08:51.517350Z'
    model_source: from-import
    model_path: models/from-import/model.pt
    input_type: image
    input_path: data/uploads/predictions/20251029_000851/fruit_0000.jpg
    output_path: predictions/inf-20251029-040851
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: true
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 1
      avg_inference_time_ms: 187.72
      classes_detected:
      - cake
  inf-20251029-041009:
    id: inf-20251029-041009
    created: '2025-10-29T04:10:09.803182Z'
    model_source: from-import
    model_path: models/from-import/model.pt
    input_type: image
    input_path: data/uploads/predictions/20251029_001009/fruit_0000.jpg
    output_path: predictions/inf-20251029-041009
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: true
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 1
      avg_inference_time_ms: 281.61
      classes_detected:
      - cake
  inf-20251029-041125:
    id: inf-20251029-041125
    created: '2025-10-29T04:11:25.177668Z'
    model_source: from-import
    model_path: models/from-import/model.pt
    input_type: image
    input_path: data/uploads/predictions/20251029_001125/fruit_0000.jpg
    output_path: predictions/inf-20251029-041125
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: true
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 1
      avg_inference_time_ms: 316.8
      classes_detected:
      - cake
  inf-20251101-034818:
    id: inf-20251101-034818
    created: '2025-11-01T03:48:18.473590Z'
    model_source: from-import
    model_path: models/from-import/model.pt
    input_type: image
    input_path: data/uploads/predictions/20251031_234818/grizzly9.jpg
    output_path: predictions/inf-20251101-034818
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: false
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 1
      avg_inference_time_ms: 210.82
      classes_detected:
      - sheep
  inf-20251101-034836:
    id: inf-20251101-034836
    created: '2025-11-01T03:48:36.665210Z'
    model_source: from-import
    model_path: models/from-import/model.pt
    input_type: image
    input_path: data/uploads/predictions/20251031_234836/grizzly46.jpg
    output_path: predictions/inf-20251101-034836
    config:
      conf_threshold: 0.25
      iou_threshold: 0.45
      device: cpu
      save_txt: true
      save_img: true
      classes: null
      batch_size: 16
    status: completed
    stats:
      total_images: 1
      total_detections: 1
      avg_inference_time_ms: 133.89
      classes_detected:
      - bear
